### PR TITLE
Add Access-Control-Allow-Origin header to all responses

### PR DESCRIPTION
**Pull request by AlexMeuer**
Add middleware that just adds an `Access-Control-Allow-Origin: *` header to all responses.

Also initialise go module

### CODE REVIEW

**Comment by jbrunton** [comment]
This would be very helpful. My team is currently working to "hello world" the infrastructure for a new set of services, but we just realised this container won't work for us since the web client and API will be on different subdomains.

**Comment by AlexMeuer** [comment]
I wouldn't hold your breath waiting for this to be merged. The last commit to `master` was years ago.

Better to `go install` the fork or clone it and make your own docker image.

**Comment by vincetse** [comment]
Pardon my tardiness reviewing this.  Merging it now.  Thanks!

**Comment by vincetse** [comment]
Btw, just a heads-up that I'm working on building the images with the change in this PR.  Docker Hub doesn't have the free builds anymore, so I'm taking the opportunity to update the build process with GitHub Actions.

**Comment by vincetse** [comment]
Alright, folks.  I finally got the GitHb Actions builds working.  Unfortunately, I had to migrate to the GitHub Container Registry since Docker Hub started throttling free users.  I just [tagged 2.3.0](https://github.com/infrastructure-as-code/docker-hello-world/releases/tag/2.3.0) with the PR from @AlexMeuer.  Again, please pardon my tardiness.

```
docker pull ghcr.io/infrastructure-as-code/hello-world:2.3.0
```

**Comment by vincetse** [comment]
Hi again, folks.  Just thought I'll give you a heads-up that I figured out how to use Docker Hub from GitHub Actions.  I added 2 images in the automated builds:

1. ghcr.io/infrastructure-as-code/hello-world
2. infrastructureascode/hello-world

I also retagged 2.3.0.  Pardon my back and forth here.

**Pull request merged**
